### ISSUE TITLE
Datenbanklogik sicher stellen

### ISSUE THREAD

**Issue by ClemenSGa** [EliasC10/MobiDic#3]
die Beziehungen zwischen den einzelnen Datenbanken überprüfen

**Comment by EliasC10** [comment]
foreign key constraint zwischen Supervisor & Institution hergestellt.

**Comment by EliasC10** [comment]
fkc zwischen Cliet & Institution hergestellt.

**Comment by ClemenSGa** [comment]
fkc zwischen Category <-> EntryCategory <-> Entry hergestellt.

**Comment by EliasC10** [comment]
Constraints hergestellt
