### ISSUE TITLE
API Schnittstellen zum Lesen und Speichern der Daten

### ISSUE THREAD

**Issue by ClemenSGa** [EliasC10/MobiDic#4]
per Android APP werden die Daten an das Backend übergeben bzw. ausgelesen

**Comment by ClemenSGa** [comment]
Nr. 1: Betreuer Log-In (API-Antwortet mit dem JSON-Objekt Betreuer)....in work

**Comment by EliasC10** [comment]
Nr. 1: Login mit JWT umgesetzt.. API antwortet nur mehr mit gültigem JWT

**Comment by EliasC10** [comment]
Nr. 2: API-Request mit supervisor_id um die clients einer bestimmten institution zu erhalten...in work

**Comment by EliasC10** [comment]
Nr. 2: done

**Comment by EliasC10** [comment]
Nr. 3: API-Request für categories um alle categories zu erhalten

**Comment by EliasC10** [comment]
Nr. 3: done

**Comment by EliasC10** [comment]
Nr. 4: API-Request für entries um alle Entry zu der passenden institution des supervisors zu erhalten...in work

**Comment by EliasC10** [comment]
Nr. 4: done

**Comment by EliasC10** [comment]
Nr. 5: Entry erstellen, automatisierte Untereinträge in (ClientEntry & EntryCategory)

**Comment by EliasC10** [comment]
Nr. 5: done ( Eintrag funktioniert nun inklusive Einträge in ClientEntry und EntryCategory)

**Comment by EliasC10** [comment]
alle Relations hergestellt, issue closed
